(let ((total 0)
      (index 0))
  (while (< index 10000 )
    (setq total (+ index 10))
    (when (< total 9000.0)
      (setq total (+ total 4.2))
      (when (> index 4000.0)
        (setq total (+ total 3))))
    (setq index (+ index 1)))
  (print total))
